services:
  postgres:
    image: postgres:18-alpine
    container_name: postgres
    env_file: 
      - ./server/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  server:
    build: ./server
    container_name: sparc-server
    environment:
      TZ: Asia/Kolkata
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3030:3030"
  client:
    build: ./client
    container_name: sparc-client
    environment:
      TZ: Asia/Kolkata
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  postgres_data: