server {
        listen 80;
        server_name 127.0.0.1;

        # serving static frontend client/build/static/ files
        location /static/ {
                root /usr/share/nginx/html;

                expires 1y;
                add_header Cache-Control "public, max-age=31536000, immutable";
        }

        # serving dynamic frontend client/build/index.html file
        location = /index.html {
                root /usr/share/nginx/html;

                add_header Cache-Control "no-cache, no-store, must-revalidate";
        }

        # frontend fallback
        location / {
                # error_log /var/log/nginx/sparc/client_error.log;
                root /usr/share/nginx/html;
                index index.html;

                try_files $uri /index.html;

                add_header Cache-Control "no-cache";
        }

        # serving backend (login)
        location = /api/login/auth {

                # error_log /var/log/nginx/sparc/server_error.log;
                client_max_body_size 1M;

                proxy_pass http://backend;

                add_header Cache-Control "no-cache";
        }

        # serving backend
        location /api/ {
                limit_req zone=api_limit burst=10;

                # error_log /var/log/nginx/sparc/server_error.log;
                client_max_body_size 1M;

                proxy_pass http://backend;

                add_header Cache-Control "no-cache";
        }
}

upstream backend {
        server sparc-server:3030;
        keepalive 32;
}