import config from "../../../client/src/configuration/config.js";

const tips = [
    "Diversify your income sources to increase financial stability.",
    "Save at least 20% of your monthly income for emergencies.",
    "Avoid impulse buying to save more money.",
    "Invest in yourself to increase your earning potential.",
    "Set your expense limits to track your spending.",
    "Use bonuses or extra income to pay off debt or invest.",
    "Set financial goals to keep yourself motivated.",
    "Create passive income streams to boost your earnings.",
    "Avoid lifestyle inflation to save more money.",
    "Invest in assets that appreciate over time.",
    "Revisit your salary annually and negotiate for a raise if possible.",
    "Dedicate part of any unexpected income to your financial goals.",
    "Consider shared accommodation to lower rent costs.",
    "Use public transport or carpool to save on transportation costs.",
    "Buy in bulk to save on groceries.",
    "Use energy-efficient appliances to save on electricity bills.",
    "Avoid eating out to save on food costs.",
    "Use cashback apps or credit cards to save on shopping.",
    "Regularly compare rental prices in your area for better deals.",
    "Claim all tax deductions available to you, such as medical and education expenses.",
    "Invest in tax-saving instruments like ELSS, PPF, or NSC.",
    "Buy insurance policies that cover your specific needs.",
    "Avoid unnecessary insurance policies to save on premiums.",
    "Invest in SIPs for long-term wealth creation.",
    "Diversify your investment portfolio to reduce risk.",
    "Maintain proper documentation for tax benefits on home loans or insurance premiums.",
    "Set up an emergency fund to cover unexpected expenses.",
    "Avoid taking on unnecessary debt to maintain financial health.",
    "Use balance transfer facilities to reduce high-interest debt.",
    "Avoid using credit cards for unnecessary expenses.",
    "Regularly review your investment portfolio for performance.",
    "Avoid withdrawing from your retirement fund unless absolutely necessary.",
    "Invest in health insurance to cover medical expenses.",
    "Consider term insurance for financial protection of your dependents.",
    "Avoid investing in high-risk instruments without proper research.",
    "File your income tax returns (ITR) on time to avoid penalties.",
    "Choose term insurance instead of expensive endowment policies.",
    "Review and update your insurance policies yearly.",
    "Start investing early to take advantage of compound interest.",
    "Allocate a fixed percentage of your income to investments.",
    "Diversify your portfolio across mutual funds, stocks, and fixed deposits.",
    "Unplug electronics when not in use to save power.",
    "Switch to LED bulbs for better energy savings.",
    "Use fans instead of air conditioners wherever possible.",
    "Run washing machines and other large appliances during off-peak hours.",
    "Fix leaks and dripping taps to save water and reduce bills.",
    "Use a bucket instead of a shower to conserve water.",
    "Reuse water from RO purifiers for cleaning purposes.",
    "Use rainwater harvesting to reduce water consumption.",
    "Grow your own vegetables to save on grocery bills.",
    "Install water-saving nozzles in taps.",
    "Use solar panels to reduce electricity bills.",
    "Switch to a gas connection with cashback offers or subsidies.",
    "Use a pressure cooker to save fuel while cooking.",
    "Set up auto-payments for bills to avoid late fees.",
    "Consolidate streaming subscriptions and cancel unused services.",
    "Review your mobile or internet plan and downgrade if needed.",
    "Avoid unnecessary credit card fees by paying bills on time.",
    "Use a shopping list to avoid impulse purchases.",
    "Buy generic brands instead of expensive labels.",
    "Buy seasonal fruits and vegetables—they’re cheaper and fresher.",
    "Compare prices across local markets and online stores.",
    "Avoid shopping on an empty stomach to reduce overspending.",
    "Use discount coupons and cashback offers while shopping.",
    "Sell unused items online to make extra money.",
    "Purchase in bulk for items you use frequently.",
    "Opt for takeout instead of dining out to save on service charges.",
    "Limit eating out to special occasions only.",
    "Switch to free or lower-cost streaming platforms.",
    "Wait for festive or seasonal sales to buy expensive items.",
    "Compare prices online before making purchases.",
    "Use credit card reward points for shopping.",
    "Book flights and hotels in advance to get the best deals.",
    "Avoid peak season travel for cheaper fares.",
    "Pack light to avoid extra baggage fees while travelling via flight.",
    "Repair broken items instead of immediately replacing them.",
    "Use DIY methods for home repairs to save on professional fees.",
    "Opt for multi-purpose tools and gadgets for efficiency.",
    "Borrow rarely used tools or appliances instead of buying them.",
    "Cancel unnecessary memberships or subscriptions.",
    "Take advantage of free trials before committing to a service.",
    "Group multiple services (e.g., internet + cable) for bundled discounts.",
    "Read reviews and ratings before paying for services.",
    "Invest in quality items that last longer instead of cheap alternatives.",
    "Stick to your budget and review it regularly.",
    "Maintain an emergency fund with at least 3 months' expenses.",
    "Avoid loaning money unless you're financially stable."
];

function getRandomTips() {
    return tips.sort(() => 0.5 - Math.random()).slice(0, 3).map(tip => ({ message: tip, type: config.notificationType.tip }));
}

export default getRandomTips;